set(LJCORE ${CMAKE_CURRENT_LIST_DIR}/../jerryscript)
include_directories(${LJCORE}/jerry-core/include/)
set(LJPATH ${CMAKE_CURRENT_LIST_DIR}/../Lib)
set(LJFILES "")
set(LJFILES ${LJFILES} ${LJPATH}/jerry-libm.a)
set(LJFILES ${LJFILES} ${LJPATH}/jerry-core.a)
target_link_libraries(microbit-js ${LJFILES})
